# Generated by Django 3.2.7 on 2021-10-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lecture_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='branch',
            new_name='dep',
        ),
    ]
