# Generated by Django 3.2.7 on 2021-10-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_branch_lecture_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='dep',
            new_name='depart',
        ),
    ]
