# Generated by Django 3.2.7 on 2021-10-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dep_lecture_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='depart',
            new_name='department',
        ),
    ]
