# Generated by Django 3.2.6 on 2021-10-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_depart_lecture_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='branch',
            new_name='dep',
        ),
    ]
