# Generated by Django 3.2.6 on 2021-10-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_branch_lecture_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='dep',
            new_name='depart',
        ),
    ]
