# Generated by Django 3.2.6 on 2021-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_dep_lecture_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='depart',
            new_name='Dpt',
        ),
    ]
