# Generated by Django 3.2.6 on 2021-10-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_depart_lecture_dpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='Dpt',
            new_name='depart',
        ),
    ]
